POST http://localhost:8080/drivers HTTP/1.1
Content-Type: application/json

{
  "name": "Driver 1",
  "email": "ggg@g.com",
  "license_number": "ABC1234556-1"
}

POST http://localhost:8080/drivers HTTP/1.1
Content-Type: application/json

{
  "name": "Driver 2",
  "email": "ggg2222@g.com",
  "license_number": "ABC1234556-2"
}

GET http://localhost:8080/drivers HTTP/1.1
Content-Type: application/json


PUT http://localhost:8080/drivers/4f9338f6-fbe0-429d-9d56-68a53db880ce HTTP/1.1
Content-Type: application/json

{
  "name": "Driver UPDATE",
  "email": "gggUPDATE@g.com",
  "license_number": "ABC1234556-UPDATE"
}

GET http://localhost:8080/drivers/4f9338f6-fbe0-429d-9d56-68a53db880ce HTTP/1.1
Content-Type: application/json

DELETE http://localhost:8080/drivers/4f9338f6-fbe0-429d-9d56-68a53db880ce HTTP/1.1