POST http://localhost:8080/truckdrivers HTTP/1.1
Content-Type: application/json

{
  "name": "Truck Driver 1",
  "email": "ggg@g.com",
  "license_number": "ABC1234556-1"
}

POST http://localhost:8080/truckdrivers HTTP/1.1
Content-Type: application/json

{
  "name": "Truck Driver 2",
  "email": "ggg2222@g.com",
  "license_number": "ABC1234556-2"
}

GET http://localhost:8080/truckdrivers HTTP/1.1
Content-Type: application/json


PUT http://localhost:8080/truckdrivers/d7388c66-7d71-4c25-a4fa-94717347b1e8 HTTP/1.1
Content-Type: application/json

{
  "name": "Truck Driver UPDATE",
  "email": "gggUPDATE@g.com",
  "license_number": "ABC1234556-UPDATE"
}

GET http://localhost:8080/truckdrivers/d7388c66-7d71-4c25-a4fa-94717347b1e8 HTTP/1.1
Content-Type: application/json

DELETE http://localhost:8080/truckdrivers/d7388c66-7d71-4c25-a4fa-94717347b1e8 HTTP/1.1