POST http://localhost:8080/trucks HTTP/1.1
Content-Type: application/json

{
  "model_type": "Truck 1",
  "Year": 1990,
  "manufacturer": "VOLVO",
  "license_plate": "TRUCK1234556-1",
  "fuel_type": "diesel"
}

POST http://localhost:8080/trucks HTTP/1.1
Content-Type: application/json

{
   "model_type": "Truck 2",
  "Year": 2000,
  "manufacturer": "SCANIA",
  "license_plate": "TRUCK1234556-2",
  "fuel_type": "diesel"
}

GET http://localhost:8080/trucks HTTP/1.1
Content-Type: application/json

PUT http://localhost:8080/trucks/b5ebb3a0-d9d8-4895-996a-206a59086595 HTTP/1.1
Content-Type: application/json

{
  "model_type": "Truck UPDATE",
  "license_plate": "TRUCK1234556-UPDATE"
}

GET http://localhost:8080/trucks/b5ebb3a0-d9d8-4895-996a-206a59086595 HTTP/1.1
Content-Type: application/json

DELETE http://localhost:8080/trucks/b5ebb3a0-d9d8-4895-996a-206a59086595 HTTP/1.1