POST http://localhost:8080/trucks HTTP/1.1
Content-Type: application/json

{
  "model_type": "Truck 1",
  "Year": 1990,
  "manufacturer": "VOLVO",
  "license_plate": "TRUCK1234556-1",
  "fuel_type": "diesel"
}

POST http://localhost:8080/trucks HTTP/1.1
Content-Type: application/json

{
   "model_type": "Truck 2",
  "Year": 2000,
  "manufacturer": "SCANIA",
  "license_plate": "TRUCK1234556-2",
  "fuel_type": "diesel"
}

GET http://localhost:8080/trucks HTTP/1.1
Content-Type: application/json

PUT http://localhost:8080/trucks/c0e3e1ac-ed0c-42c5-b2b6-ad89f0e0b493 HTTP/1.1
Content-Type: application/json

{
  "model_type": "Truck UPDATE",
  "license_plate": "TRUCK1234556-UPDATE",
}

GET http://localhost:8080/trucks/c0e3e1ac-ed0c-42c5-b2b6-ad89f0e0b493 HTTP/1.1
Content-Type: application/json

DELETE http://localhost:8080/trucks/c0e3e1ac-ed0c-42c5-b2b6-ad89f0e0b493 HTTP/1.1